import React, { useEffect, useState } from 'react';
import axios from 'axios';

const API = 'http://localhost:3000/api';

export function ShiftReportPage() {
  const [reportText, setReportText] = useState<string>('');
  const [hours, setHours] = useState<number>(8);
  const [loading, setLoading] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  const fetchReport = (h: number) => {
    setLoading(true);
    axios
      .get(`${API}/reports/shift?hours=${h}`)
      .then((res) => setReportText(res.data.report))
      .catch(() => setReportText('Failed to load shift report.'))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchReport(hours);
  }, [hours]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-abyss text-starlight font-sans p-6 print:bg-white print:text-black">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header (hidden when printing) */}
        <div className="flex items-center justify-between print:hidden">
          <div>
            <h1 className="text-2xl font-display font-bold text-ion tracking-wide uppercase">
              Shift Handover Report
            </h1>
            <p className="text-xs text-dust font-mono mt-1">
              Automated operational summary generated by Mission AI (Gemini)
            </p>
          </div>
          <div className="flex items-center gap-3 font-mono text-xs">
            <a href="/" className="text-white/40 hover:text-white transition-colors">
              ← Globe
            </a>
          </div>
        </div>

        {/* Controls (hidden when printing) */}
        <div className="flex items-center justify-between bg-black/40 border border-white/10 rounded-xl p-4 print:hidden">
          <div className="flex items-center gap-2 text-xs font-mono">
            <span className="text-white/50">Time Window:</span>
            {[4, 8, 12, 24].map((h) => (
              <button
                key={h}
                onClick={() => setHours(h)}
                className={
                  hours === h
                    ? 'px-3 py-1 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 font-bold'
                    : 'px-3 py-1 rounded text-white/40 border border-white/10 hover:text-white'
                }
              >
                Last {h}h
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2 text-xs font-mono">
            <button
              onClick={copyToClipboard}
              className="px-3 py-1.5 rounded bg-white/5 hover:bg-white/10 border border-white/20 text-white/80 transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy Text'}
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-1.5 rounded bg-cyan-500/20 hover:bg-cyan-500/40 border border-cyan-500/50 text-cyan-300 font-bold transition-colors"
            >
              📄 Print / Save PDF
            </button>
          </div>
        </div>

        {/* Report Card */}
        <div className="bg-black/60 backdrop-blur border border-white/10 rounded-2xl p-8 print:bg-white print:border-none print:shadow-none print:p-0">
          <div className="border-b border-white/10 pb-4 mb-6 flex justify-between items-end print:border-black">
            <div>
              <div className="text-xs font-mono text-cyan-400 uppercase tracking-widest print:text-blue-600">
                Supernova Mission Control
              </div>
              <h2 className="text-xl font-bold font-display text-white mt-1 print:text-black">
                Operational Handover Summary
              </h2>
            </div>
            <div className="text-right font-mono text-xs text-white/40 print:text-gray-600">
              Generated: {new Date().toUTCString()}
            </div>
          </div>

          {loading ? (
            <div className="text-white/40 text-center py-12 font-mono animate-pulse text-sm">
              Generating shift handover report with Mission AI...
            </div>
          ) : (
            <div className="prose prose-invert max-w-none text-sm font-mono whitespace-pre-wrap leading-relaxed print:text-black print:prose">
              {reportText}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
